config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :dishes do
    member do
      post 'add_to_cart', as: 'add'
      post 'remove_from_cart', as: 'remove'
    end
  end
  resources :orders
  resources :users, only: ['index', 'show']

  namespace :api do
    post 'authenticate', to: 'authentication#authenticate'
    post 'orders', to: 'orders#index'
  end

  root 'dishes#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/dish.rb
class Dish < ApplicationRecord
  acts_as_paranoid
  has_and_belongs_to_many :orders
  enum day_of_the_week: [ :sunday, :monday, :tuesday, :wendesday, :thursday, :friday, :saturday, :weekday_not_specified ]
  enum dish_type: [ :first_course, :second_course, :drink ]
  mount_uploader :picture, PictureUploader

  default_scope -> { order(dish_type: :asc) }
  scope :weekday, ->(weekday) { where(day_of_the_week: day_of_the_weeks[weekday]) }
  scope :dish_type, ->(dish_type) { where(dish_type: dish_types[dish_type]) }
  scope :today, -> { where('day_of_the_week = ? OR single_day = ?', Date.today.wday, Date.today) }
  scope :not_today, -> { where('day_of_the_week != ? AND (single_day is null OR single_day != ?)', Date.today.wday, Date.today) }
  scope :drinks, -> { dish_type(:drink) }
  scope :first_courses, -> { dish_type(:first_course) }
  scope :second_courses, -> { dish_type(:second_course) }

  validates :name, presence: true
  validates :dish_type, presence: true
  validates :price, presence: true, numericality: { greater_than: 0 }
  validate  :picture_size, :day_selected, :single_day_not_in_past

  def available_today?
    Dish.day_of_the_weeks[day_of_the_week] == Date.today.wday || single_day == Date.today
  end

  private

  def picture_size
    return if picture.nil? || picture.blank?
    if picture.size > 5.megabytes
      errors.add(:picture, 'should =>  be less than 5MB')
    end
  end

  def day_selected
    if (day_of_the_week.nil? || weekday_not_specified?) && single_day.nil?
      errors[:base] << 'Specify day of the week or single day when this dish is available for users'
    end
  end

  def single_day_not_in_past
    return if single_day.nil? || single_day.blank? || !weekday_not_specified?
    if single_day.past?
      errors.add(:single_day, 'cannot be in past')
    end
  end
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  include OrdersHelper
  before_action :authenticate_user!, except: [:index, :show]
  load_and_authorize_resource
  skip_authorize_resource only: [:index, :show]
  before_action :set_dish, only: [:show, :edit, :update, :destroy, :add_to_cart, :remove_from_cart]

  DISHES_PER_PAGE = 10

  # GET /dishes
  # GET /dishes.json
  def index
    @dishes = Dish.all
    @weekdays = Dish.day_of_the_weeks.keys.delete_if { |key| key == 'weekday_not_specified' }
    dish_filter = params[:dish_filter]
    if !dish_filter.nil? && dish_filter.is_a?(String) && !dish_filter.empty?
      dish_filter.downcase!
      if @weekdays.include? dish_filter
        @dishes = @dishes.weekday(dish_filter.to_sym)
      elsif dish_filter == 'today'
        @dishes = @dishes.today
      end
    end
    page = params[:page].is_a?(String) && params[:page].is_positive_i? ? params[:page].to_i : 1
    @dishes = @dishes.paginate(per_page: DISHES_PER_PAGE, page: page)
  end

  # GET /dishes/1
  # GET /dishes/1.json
  def show
  end

  # GET /dishes/new
  def new
    @dish = Dish.new
  end

  # POST /dishes/add/:id
  def add_to_cart
    @order = current_order
    if @order.validate_new_dish(@dish) && @order.valid?
      @order.dishes << @dish
      @order.save
      session[:order_id] = @order.id
    end
    #redirect_to dishes_url
  end

  # POST /dishes/remove/:id
  def remove_from_cart
    @order = current_order
    @order.dishes.delete(@dish)
    if @order.save
      session[:order_id] = @order.id
    end
    #redirect_to edit_order_url(@order)
  end

  def create
    @dish = Dish.new(dish_params)
    if (@dish.weekday_not_specified? || @dish.day_of_the_week.nil?) && @dish.single_day.nil?
      @dish.single_day = Date.today
    end
    respond_to do |format|
      if @dish.save
        format.html { redirect_to @dish, notice: 'Dish was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /dishes/1
  # PATCH/PUT /dishes/1.json
  def update
    respond_to do |format|
      if params[:dish][:remove_picture] == 1
        @dish.remove_picture!
      end
      if @dish.update(dish_params)
        format.html { redirect_to @dish, notice: 'Dish was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /dishes/1
  # DELETE /dishes/1.json
  def destroy
    @dish.destroy
    respond_to do |format|
      format.html { redirect_to dishes_url, notice: 'Dish was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_dish
    @dish = Dish.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def dish_params
    params.require(:dish).permit(:name, :picture, :dish_type, :day_of_the_week, :price, :single_day, :remove_picture)
  end
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/views/dishes/_dishes.html.haml
%table
  %thead
    %tr
      %th Name
      %th Price
      %th Type
      %th
      %th
      %th
      %th

  %tbody
    - dishes.each do |dish|
      %tr{ data: { id: dish.id } }
        %td= dish.name
        %td= dish.price.round(2)
        %td= dish.dish_type.humanize
        %td= link_to 'Show', dish
        - if admin?
          %td= link_to 'Edit', edit_dish_path(dish)
          %td= link_to 'Destroy', dish, method: :delete, data: { confirm: 'Are you sure?' }
        - if not_admin?
          -if is_order
            %td= link_to 'Remove from cart', remove_dish_path(dish), method: :post, remote: true, class: 'btn btn-danger'
          -else
            %td= link_to 'Add to cart', add_dish_path(dish), method: :post, remote: true, class: 'btn btn-success' if dish.available_today?

app/views/dishes/_form.html.haml
= form_for @dish do |form|
  #errors
    =render 'layouts/errors', entity: @dish, entity_name: 'dish'

  .field
    = form.label :name
    = form.text_field :name, class: 'form-control'
  .field
    = form.label :price
    = form.number_field :price, :class => 'text_field form-control', step: 0.01, min: 0.01
  .field
    = form.label :day_of_the_week
    = form.select :day_of_the_week, Dish.day_of_the_weeks.map { |key, value| [key.humanize, key] }, { selected: :weekday_not_specified }, class: 'form-control'
  .field
    = form.label :dish_type
    = form.select :dish_type, Dish.dish_types.map { |key, value| [key.humanize, key] }, {}, class: 'form-control'
  .field
    = form.label :single_day
    = form.date_field :single_day, class: 'form-control'
  %span.picture
    = form.label :picture
    = form.file_field :picture, accept: 'image/jpeg,image/gif,image/png', class: 'js-picture form-control'
    = form.hidden_field :picture_cache
    = image_tag(@dish.picture_url, size: '300x200') if @dish.picture?
  - if !@dish.new_record? && @dish.picture?
    %p
      %label
        = form.check_box :remove_picture
        Remove picture
  :javascript
    $('.js-picture').bind('change', function() {
        var size_in_megabytes = this.files[0].size/1024/1024;
        if (size_in_megabytes > 5) {
            alert('Maximum file size is 5MB. Please choose a smaller file.');
        }
    });

  .actions
    = form.submit 'Save', class: 'btn btn-primary'

app/views/dishes/add_to_cart.js.erb
<% if @order.errors.blank? %>
  $("p.notice").html("<%=@dish.name %> was added to your cart");
  $("#errors").html("")
<% else %>
  $("p.notice").html("");
  $("#errors").html("<%= escape_javascript(render('layouts/errors', entity: @order, entity_name: 'order')) %>")
<% end %>

app/views/dishes/edit.html.haml
%h1 Editing dish

= render 'form'

= link_to 'Show', @dish
\|
= link_to 'Back', dishes_path

app/views/dishes/index.html.haml
= javascript_include_tag 'pagination'
%h1 Listing dishes

#errors

.links
  = link_to 'All', dishes_path
  = link_to 'Today', dishes_path(dish_filter: 'today')
  - @weekdays.each do |weekday|
    = link_to weekday.humanize, dishes_path(dish_filter: weekday)


#dishes
  =render 'dishes/dishes', dishes: @dishes, is_order: false
=will_paginate @dishes

%br

- if admin?
  = link_to 'New Dish', new_dish_path

app/views/dishes/new.html.haml
%h1 New dish

= render 'form'

= link_to 'Back', :back

app/views/dishes/remove_from_cart.js.erb
<% if @order.errors.blank? %>
  $("p.notice").html("<%=@dish.name %> was removed from your cart")
  <% if @order.dishes.blank? %>
    $("#order").html("<%= escape_javascript(render('orders/form')) %>")
  <% else %>
    $("#errors").html("");
    $("#summary_price").html("<%=@order.total_price.round(2) %>");
    $('tr[data-id=<%=@dish.id %>]').hide()
  <% end %>
<% else %>
  $("p.notice").html("");
  $("#errors").html("<%= escape_javascript(render('layouts/errors', entity: @order, entity_name: 'order')) %>")
<% end %>

app/views/dishes/show.html.haml
%p
  %strong Name:
  = @dish.name

%p
  %strong Price:
  = @dish.price.round(2)

%p
  %strong Dish type:
  = @dish.dish_type.humanize

%p
  %strong Available at:
  - if @dish.weekday_not_specified?
    = @dish.single_day
  - else
    = @dish.day_of_the_week.humanize

%span.picture
  = image_tag(@dish.picture_url, size: '300x200') if @dish.picture?

%div
  - if admin?
    = link_to 'Edit', edit_dish_path(@dish)

  = link_to 'Back', :back