config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :dishes do
    member do
      post 'add_to_cart', as: 'add'
      post 'remove_from_cart', as: 'remove'
    end
  end
  resources :orders
  resources :users, only: ['index', 'show']

  namespace :api do
    post 'authenticate', to: 'authentication#authenticate'
    post 'orders', to: 'orders#index'
  end

  root 'dishes#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_errors.html.haml
- if entity.errors.any?
  #error_explanation
    %h2= "#{pluralize(entity.errors.count, "error")} prohibited this #{entity_name} from being saved:"
    %ul
      - entity.errors.full_messages.each do |message|
        %li= message

app/views/layouts/_footer.html.haml
%footer.footer

app/views/layouts/_header.html.haml
%body
  %header.navbar.navbar-fixed-top.navbar-inverse
    .container
      %nav
        %ul.nav.navbar-nav.navbar-right
          %li= link_to "Dishes", dishes_path
          %li= link_to "Orders", orders_path
          %li= link_to "Cart", new_order_path
          - if user_signed_in?
            - if current_user.has_role? :admin
              %li= link_to "Users", users_path
            %li.dropdown
              %a#dropdownMenuLink.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                Account
                %b.caret
              %ul.dropdown-menu{"aria-labelledby" => "dropdownMenuLink"}
                %li.dropdown-item= link_to "Profile", current_user
                %li.dropdown-item= link_to "Edit profile", edit_user_registration_path
                %li.divider
                %li.dropdown-item
                  = link_to "Log out", destroy_user_session_path, method: :delete
          - else
            %li= link_to "Log in", new_user_session_path

app/views/layouts/_rails_default.html.haml
= csrf_meta_tags
= stylesheet_link_tag    'application', media: 'all', |
  'data-turbolinks-track': 'reload'                   |
= javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

app/views/layouts/_shim.html.haml
/[if lt IE 9]
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title LunchOrdering
    = render 'layouts/rails_default'
    = render 'layouts/shim'
  %body
    = render 'layouts/header'
    %p.notice= notice
    %p.alert= alert
    .container
      = yield
      = render 'layouts/footer'